### ISSUE TITLE
Compressed SVG (svgz) icons cannot be manually assigned to app in "Create custom launcher"

### ISSUE THREAD

**Issue by milankni** [robint99/dock-applet#10]
The title says it all.

Putting
Icon=/full/path/to/digikam.svgz
in $HOME/.local/share/apps/mda_digikam.desktop leads to crash of the applet (it is not displayed at all after "mate-panel --replace".

Using Icon=digikam or Icon=/full/path/to/digikam.svg works just fine.

BTW, digiKam's icon is not caught by the dock-applet when the app is running.

Arch Linux, MATE desktop.

**Comment by robint99** [comment]
I've had a look at this now. It seems that .svgz icons aren't supported by GTK2 - I guess they're a KDE thing? - so I've changed the custom launcher dialog to allow only .xpm, .png and .svg files to be selected.

As for digikam's icon not being recognised, I've fixed this too.

Both changes have been pushed to github and a new version of the applet will be released in the next week or two when I've fixed some other outstanding issues. In the meantime, you can get digikam working properly with the dock by copying /usr/share/applications/kde4/digikam,desktop to ~/.local/share/applications. If did manage to succesfully create a custom launcher you'll need to delete this first - just delete any .desktop file in ~/.local/share/applications that start with 'mda_'

**Comment by milankni** [comment]
Yeah, SVGZ is probably a KDE speciality, luckily there are still standard PNGs...

I updated the GIT version and the digikam.desktop is now looked up from the /usr/share/applications/kde4 correctly.

Thanks!

**Comment by milankni** [comment]
I was too fast to confirm that all is okay: the digikam (and other kde4 apps in /usr/share/applications/kde4/blabla.desktop) do have an icon in Dock Applet, when the app runs, also the pinning works. However, after re-starting the panel (log-off and on or mate-panel --replace), the pinned icon is not shown.
I checked in dconf-editor and 'digikam.desktop' or 'showfoto.desktop' is still listed among the other pinned apps in the dock. It is just not visible.

**Comment by robint99** [comment]
I've sorted this out now and the icons survive reboots and logouts etc. The code's up on github if you want to give it a try...

Cheers

**Comment by milankni** [comment]
It works now. Thanks.
