### ISSUE TITLE
(enhancement) Show list of open windows on hover above the dock icon

### ISSUE THREAD

**Issue by milankni** [robint99/dock-applet#11]
It would be nice to show a list of currently open windows (if there are more than one), when the user hovers mouse pointer over the docked icon.

Currently, the user has to right-click and choose from the top of the menu.

Left-click behaviour has other use: a) it brings up all the windows, while choosing from a list applies focus only on a single window; b) it does not help when the windows are maximised to full screen or otherwise stacked over themselves.

**Comment by marsjaninzmarsa** [comment]
+1

**Comment by robint99** [comment]
Added to my to-do list! While it would be nice to have thumbnails of the open windows in the list, I'm not sure how complicated this would be to implement or whether it would only work with composited window managers. So I think it best if the window list is quite simple to begin with - just icons and the window titles.

Cheers

**Comment by milankni** [comment]
Yeah, a simple list of open windows (icon&title or only a title for the start) is what I am looking for.

P.S. I actually switched to MATE because the accelerated desktops do not work well through remote access (X2Go in my case). MATE w/ marco does so far.

**Comment by robint99** [comment]
I've now added window lists to the applet and the new version (0.63) has them!

**Comment by milankni** [comment]
Nice. The first impression is that it works as expected. Thanks.
