### ISSUE TITLE
Support for highlighted windows

### ISSUE THREAD

**Issue by marsjaninzmarsa** [robint99/dock-applet#12]
I'll be glad if icon in dock can handle window highlight action (eg on new message in IM/IRC) and highlight the background, pulsing background would be perfect. :)

Ough, and if highlighted window is on another workspace and "Display unpinned apps only from current workspace" is selected, icon could appear on all workspaces allowing quick switch to app.

**Comment by robint99** [comment]
I don't think this would be too difficult to implement so it's another thing that's now on my to-do list...

**Comment by robint99** [comment]
I've just committed code to allow this, and the app's icon in the dock now flashes when it needs attention...

**Comment by marsjaninzmarsa** [comment]
Kudos!
