### ISSUE TITLE
user launcher ignored when system-wide launcher is present

### ISSUE THREAD

**Issue by karas84** [robint99/dock-applet#15]
Consider the following use-case:
- A program is installed system-wide, and has it's own launcher in ```/usr/share/applications/<appname>.desktop```
- A user wants to customize the icon and creates a custom launcher in  ```~/.local/share/applications/<appname>.desktop```
- The user launches the program but its custom icon is not used (the system-wide is used instead)

In this scenario deleting (or renaming) the system-wide desktop file results in the user icon being used, but it's not a possible solution. Is this on purpose? Should the user launcher be preferred?

**Comment by NoXPhasma** [comment]
Yes, I think the user launcher should be preferred. The same way the Desktop usually prefer them.

**Comment by robint99** [comment]
I'm implemented this now, and the latest version of the applet (0.63) has it included.
