### ISSUE TITLE
Some Steam games are not shown in the dock

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/dock-applet#17]
I have the problem that some Steam games are not shown in the dock. It is not to all of them, but some are never shown in the dock and can only be reached by ALT + TAB.

Some games for example are [ARK: Survival evolved](http://store.steampowered.com/app/346110/), [Volgarr the Viking](http://store.steampowered.com/app/247240/), [Worms Clan Wars](http://store.steampowered.com/app/233840/).

I'm not sure why this happens, but I think it could be because that games do not have a icon, nor a launcher.

Please tell me what informations you need on this to find out what's the cause. I'm using the latest commit.

***
Linux Mint 17.2 x64
Mate 1.10

**Comment by robint99** [comment]
I've seen this too  - Steam launches apps in a weird way, and put shortcuts in non-standard locations. I'm going to  have a go at implementing some sort of solution when I've finished the current round of changes I'm working on.

Cheers,

**Comment by robint99** [comment]
Closing this because I've opened a generic issue for reporting apps that the dock doesn't work with. Have already added a quick comment about steam apps on there...
