### ISSUE TITLE
0.63 Shows Wine Wordpad Icon for IPython QT console.

### ISSUE THREAD

**Issue by SerGIlles** [robint99/dock-applet#23]
When I run IPython QT console the applet seems to consider it Wine Wordpad.
0.62 had a similar problem with IPython QT console - it could not be started from it's pinned icon.

Manjaro 64bit Linux, installed the applet via AUR4.

**Comment by helamsirrine** [comment]
I have a similar problem with the latest build of Popcorn Time. It launches fine from the pinned launcher but it it opens a new icon in the dock that is labeled winebrowser. I ran this past the popcorntime people, but upon checking my processes I realized that wine was not actually running. It seems the applet is not detecting it properly.

**Comment by NoXPhasma** [comment]
For me a lot of programs are shown as the QuickTime Player, especially games. I'm not talking about games running with wine though, native games which get the Icon and the name QuckTime Player.

**Comment by robint99** [comment]
I've just released a new version of the applet(0.64)  which fixes all of these problems - there was in particular a problem with wine programs as you all might have noticed....

I've tested everything on Arch, Ubuntu 15.10 and Mint 17.2. Note - on Mint the dock still misidentifies Mint iPython as Mate Terminal but so does the window list applet, so there must be a problem with the way Mint implements iPython.

I've also now created a new issue which is just for reporting problems where the dock doesn't recognize apps or their icons, so if you have any more problems just add a comment there :)
