### ISSUE TITLE
Icon for an application started from Evolution mail client is not shown.

### ISSUE THREAD

**Issue by milankni** [robint99/dock-applet#25]
When I open attachment of email in Evolution (be it PDF, LibreOffice or a compressed document), no icon appears for the application which handled the document type (Adobe Reader, LibreOfice, Atril, Engrampa).

If the application is already running (run separately, e.g. from start menu), there are two windows of the same application, however the indicator shows only one - in other words, the instance run from Evolution remains unmanaged by the dock panel.

P.S. Interestingly, I found one application where the above bug does not appear: GIMP.

**Comment by robint99** [comment]
I've just released V0.64 which includes quite a few improvements to the way the dock recognises and manages windows, and this seems to fix this issue (tested on Arch, Ubuntu 15.10 and Mint 17,2).
Give it a go and let me know how you get on.

Incidentally, I've created a new issue which is just for reporting problems where the dock doesn't recognize apps or their icons, so if you have any more problems just add a comment there :)

**Comment by milankni** [comment]
The reported issue is indeed solved! I'll get back if I spot other problems.
