### ISSUE TITLE
Ubuntu Wily (15.10) support?

### ISSUE THREAD

**Issue by abrowne** [robint99/dock-applet#26]
The applet seems to compile ok, but I cannot add it to my panel.

Might be related to Ubuntu Wily [dropping gir1.2-wnck-1.0](http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/libwnck/wily/revision/93)?

**Comment by robint99** [comment]
That could well be the problem - you can download the 14.10 version from
here http://packages.ubuntu.com/utopic/libs/gir1.2-wnck-1.0  This works
with 15.04 but I haven't tried it with wily yet...

If you still have problems try
running /usr/lib/mate-applets/mate-dock-applet/dock_applet.py from a
terminl and see if you get any error messages.

Cheers...

**Comment by robint99** [comment]
I've now been able to try the applet on 15.10 and it works. Aside from installing gir1,2-wnck you'll also need to sudo apt-get install libglib2.0-dev and redo the automake, autoreconf steps etc. That should get you up and running, but if not, just let me know. 

Hopefully these steps won't be necessary once the webupd8 ppa is updated for wily.

Screenshot below
![wily](https://cloud.githubusercontent.com/assets/10033637/10391779/31dae710-6e79-11e5-86eb-cccc8acce38a.png)

**Comment by abrowne** [comment]
Thanks for looking into it. I will give it a try this weekend.

**Comment by aq2** [comment]
confirm this works for me with Ubuntu Mate 15.10

thanks!
