### ISSUE TITLE
Maximize sometimes is not working.

### ISSUE THREAD

**Issue by rigzbe** [robint99/dock-applet#29]
This is wired but after update to newest mate sometimes when I minimize windows and want to restore it it simply does not appear.
After reboot of whole system ev is working good. Its happenings randomly and is annoying ;_;
Is possible to fix it ?

**Comment by robint99** [comment]
I've just updated to MATE 1.12 and have noticed this too. Its very odd, even alt-tab stops working after a while ...

I'm looking into it now.

**Comment by robint99** [comment]
I've committed a fix for this and upped the applet version number to 0.65. I've tested it on Arch with Mate 1.12 and Ubuntu Mate 15.10 with Mate 1.10 and it seems to work fine on both. Give it a try and let me know how you get on...

**Comment by rigzbe** [comment]
I tryed and... : ) it's working, thanks

**Comment by mistra22** [comment]
Hi,
on my Arch installation with Mate 1.12 the fix does not work for Caja.
All other programs (I've tried) are working.

**Comment by mistra22** [comment]
Hi,
on my Arch installation with Mate 1.12 the fix does not work for Caja.
All other programs (I've tried) are working.

**Comment by robint99** [comment]
I identified some issues with minimizing and maximising windows on multiple workspaces and have fixed them in the latest version of the applet (V0.66). Give it a try and let me know if you run into any more problems.

**Comment by rigzbe** [comment]
I got some errors when installing on Arch, 4.3
when 
```
automake --add-missing && auroreconf:
```
```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
```

applet didnt appear after install
i typed:
```
python(3) /usr/lib/mate-applets/mate-dock-applet/dock_applet.py
```

and got:
```
/usr/lib/python3.5/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
/home/musk/.themes/Add-Waiter-Dark/gtk-2.0/gtkrc:438: Unable to locate image file in pixmap_path: "Handles/handle-vertical.png"
/home/musk/.themes/Add-Waiter-Dark/gtk-2.0/gtkrc:441: Overlay image options specified without filename

(dock_applet.py:7858): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(dock_applet.py:7858): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/home/musk/.themes/Add-Waiter-Dark/gtk-2.0/gtkrc:1312: Unable to locate image file in pixmap_path: "spin-bg-rtl-up-acive.png"
/home/musk/.themes/Add-Waiter-Dark/gtk-2.0/gtkrc:1318: Background image options specified without filename
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dom_color.py", line 8, in <module>
    import Image
ImportError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 53, in <module>
    import dock
  File "/usr/lib/mate-applets/mate-dock-applet/dock.py", line 64, in <module>
    import dock_color_changer
  File "/usr/lib/mate-applets/mate-dock-applet/dock_color_changer.py", line 39, in <module>
    import dom_color
  File "/usr/lib/mate-applets/mate-dock-applet/dom_color.py", line 10, in <module>
    from PIL import Image
ImportError: No module named 'PIL'
```

also getting this in older versions :<

**Comment by rigzbe** [comment]
Get this working (for new version to) after installing:
```
python-scipy, python2-scipy, python-pillow  and python2-pillow
```

:)

**Comment by robint99** [comment]
The package in the AUR was updated with the new dependencies for the 0.66 release and I updated the Changelog and README also.  With hindsight, I should probably have made a more prominent announcement of the new dependencies to make sure that more people were aware of them. Sorry about that...

By the way, you should should only need the Python 3 packages of PIL and scipy, and not the Python 2 packages.
