### ISSUE TITLE
When using compiz as WM, windows can't be unminimized

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/dock-applet#3]
When I use compiz as Window Manager, minimized windows can't be unminimized by a click on the icon in the Dock Applet. With the default Window manager Marco it's working fine though.

I also miss some options in this Applet:
- A key binding to open a new window instance, like Shift + Left click, on a already opened windows
- An option to show only windows on the current Monitor. I'm using a multi monitor setup and the default window list of Mate offers me an option to only show windows of the current Desktop.

---
Linux Mint 17.1 x64
Mate version 1.8.1

**Comment by mickey-megabyte** [comment]
compiz and un-minimise working fine for me Ubuntu MATE 15.04

+1 for open new instance - middle-click would be a great keybinding

**Comment by NoXPhasma** [comment]
[**@mickey-megabyte**](https://github.com/mickey-megabyte) commented on [20. Mai 2015 12:30 MESZ](https://github.com/robint99/dock-applet/issues/3#issuecomment-103837994 "2015-05-20T10:30:29Z - Replied by Github Comment Enhancer"):
> compiz and un-minimise working fine for me Ubuntu MATE 15.04

Ok, I found out that I can unminimize a window, but I need to click on a different window in the Dock Applet before. Unminimize a window after minimizing it and not click on a different opened window, doesn't work here. Could you try if this is the same behaviour on your system?

I'm using Compiz version 0.9.11.3.

**Comment by mickey-megabyte** [comment]
on my system, the dock minimizes and un-minimizes correctly regardless of order.

compiz 0.9.12.1

**Comment by NoXPhasma** [comment]
Ok, then it might be a bug in the compiz version maybe.

**Comment by robint99** [comment]
I'll check the compiz issue on both of my setups and in Virtualbox as soon as I get the chance and will start having a look at multi monitor support too.

Middle clicking/shift left click to launch a new window sounds like an excellent idea. It's trivial to implement so you can expect to see it in the next version!

**Comment by NoXPhasma** [comment]
Great, thanks for your work!

**Comment by robint99** [comment]
I can't seem to duplicate this. I'm running Linux Mint 17.1, 64-bit, Mate 1.8.1 and Compiz 1:0.9.11.3 (same as you) and minimizing/unminimizing works find. 

Are there any particular apps that this happens with, or could it be something to do with the number of windows an app has open?

**Comment by NoXPhasma** [comment]
No it happens to every window, no matter how many I have opened of them. It also happens on both Dock Applets I'm using. One on each Mate-panel, I have one panel on each of my 2 Monitors. It also happens if I only use one Dock Applet at all.

It also doesn't matter if I minimize the window on the right screen and try to unminimize it on the left. I always need to have focus on a different window or the desktop before I can unminimize it again.

I've tried to find out if this might be produced by one of the Compiz Addons and disabled a lot I don't need for proper usage. But this doesn't help.

I will post some more detailed system informations, maybe that helps:
>GPU: Nvidia GTX 660 (Nvidia proprietary Driver 349.16)
>CPU: AMD FX-8350
>Kernel: 3.16.0-38-generic

**Comment by NoXPhasma** [comment]
So I found out this is caused by the "Keep previews of minimized windows" option of the Workaround Addon of Compiz. When I disable it everything works like expected.

**Comment by robint99** [comment]
Thanks for that - I've can duplicate the problem now. There seems to be a bug with that particular option in Compiz which causes a window to report itself as being active even when it's minimized. It's easy to put a workaround in the applet though (just one line of code) so I'll add it to the next version.

Thanks again for your help!
