### ISSUE TITLE
Icon not showing on my own .desktop files

### ISSUE THREAD

**Issue by ekner** [robint99/dock-applet#30]
I've made a couple of .desktop files in ~/.local/share/applications. In the applications menu and in Docky their associated icons are showing properly, but not in this dock. There I get this icon instead:

![icon-unknown](https://cloud.githubusercontent.com/assets/3149300/11153689/d8fca51a-8a3a-11e5-852a-4eb5e37226db.png)

Example of .desktop file:

    [Desktop Entry]
    Name=TeamSpeak
    Exec=/home/gustav/program/teamspeak/ts3client_runscript.sh
    Icon=/home/gustav/program/teamspeak/teamspeak.png
    Type=Application

**Comment by nelson6e65** [comment]
I recently updated (build from master, because there is nor rpm for Fedora 21 32bit), and I'm having this issue in some apps (like Atom Editor). Also, some applications are not tracked in the bar (gik).

**Comment by ekner** [comment]
Yeah, some apps are not showing up for me as well. Software updater and opera developer among others. But they are showing in the regular Window List.

**Comment by robint99** [comment]
If you ever have an app where the dock doesn't show the icon properly, what you can do is:

**Comment by nelson6e65** [comment]
I'm using Fedora 21, 32 bits.
Ok... I'l try that.

**Comment by ekner** [comment]
After I followed your steps, the program isn't showing up at all.

My system it: Ubuntu 15.10

**Comment by robint99** [comment]
I've just installed Teamspeak on my Ubuntu MATE 15.10 laptop and creating a custom launcher works fine for me...

![screenshot](https://cloud.githubusercontent.com/assets/10033637/11297574/43608882-8f71-11e5-9d62-81ad9372ae52.png)

The .desktop file the applet created in ~/.local/share/applications is 

[Desktop Entry]
Name=TeamSpeak
Type=Application
Comment=
Exec=/home/robin/Downloads/TeamSpeak3-Client-linux_amd64/ts3client_runscript.sh
Icon=/home/robin/Downloads/TeamSpeak3-Client-linux_amd64/Teamspeak_256px_555306_easyicon.net.png
StartupWMClass=TeamSpeak 3
NoDisplay=true

What version of the applet are you running? I tested with V0.65, which is the latest on git

**Comment by ekner** [comment]
I rebooted the computer and followed the steps again, now it's working. I guess I made something wrong. Anyway, Opera Developer is still now showing up at all. Now I've upgraded to V0.65.

**Comment by robint99** [comment]
I've updated the applet and it works with Opera Developer now

![screenshot](https://cloud.githubusercontent.com/assets/10033637/11365339/9da084a8-929d-11e5-9bac-ab1315f13c02.png)

The new code is already up on git so you'll need to get the latest version ('git pull origin master' should do it), recompile and reinstall it. Also, if you still have any  opera .desktop files in ~/.local/share/applications it might be an idea to delete them - that way the applet will see opera .desktop in /usr/share/applications and you'll get the New Window and New Private Window options in the dock right click, as in the screenshot above.

Hope this fixes things for you.

**Comment by ekner** [comment]
Works for me too. Thanks!
