### ISSUE TITLE
Compiling ok - but not want to start.

### ISSUE THREAD

**Issue by rigzbe** [robint99/dock-applet#31]
Hi, I moved to Void linux, I installed Dock-applet but it does not appearing in Mate panel.

I checked this command `python /usr/lib/mate-applets/mate-dock-applet/dock_applet.py'
it gave me:
########################################################################
[musk@void-live 1]$  python /usr/lib/mate-applets/mate-dock-applet/dock_applet.py
/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)

(process:32100): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 42, in <module>
    from gi.repository import MatePanelApplet
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 114, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '2.0' is already loaded
[musk@void-live 1]$ 
#######################################################################
then I checked also: `python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py'
########################################################################[musk@void-live 1]$  python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 38, in <module>
    import gi
ImportError: No module named 'gi'
[musk@void-live 1]$ 
########################################################################
 What I done wrong? I installed all dependencies.
Pls help :wink:

**Comment by robint99** [comment]
It looks like you're missing the python interface to Gtk. I'm not familiar with Void, but I think the packages you need are python-gobject2 and python-gobject. Try installing these and then run the applet again. Hopefully, that'll sort out your problems ....

**Comment by rigzbe** [comment]
I have python-gobject and 2 installed.
I run python and python3 again and
######################################################################
[musk@void-live dock-applet-master]$  python /usr/lib/mate-applets/mate-dock-applet/dock_applet.py
/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)

(process:8399): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 42, in <module>
    from gi.repository import MatePanelApplet
  File "/usr/lib/python3.4/site-packages/gi/importer.py", line 114, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '2.0' is already loaded
######################################################################


######################################################################
[musk@void-live dock-applet-master]$  python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py
/usr/lib/python3.4/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)

(process:8471): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 42, in <module>
    from gi.repository import MatePanelApplet
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/gi/importer.py", line 114, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '2.0' is already loaded
[musk@void-live dock-applet-master]$ 
######################################################################
I have no idea what can be wrong.

**Comment by robint99** [comment]
Ok, give me a day or two to  install Void linux in a virtual machine and
see what I can figure out ...

**Comment by robint99** [comment]
I've been looking at this and have got nowhere. In fact I can't even get the applet to compile on Void because of what I presume are problems with the version of autoconf that Void uses (2.69_6, which is way ahead of the 2.69-2 on my Arch box). The versions of automake and python3 are also different - automake is 1.15_4 on Void and 1.15-1 on Arch, python3 is 3.4_1 on Void and 3.5.0-2 on Arch. 

Because Void isn't exactly a mainstream distro and there's not much info on the web or in their forums, all I can suggest of is that you see if you can downgrade your version of automake and autoconf and upgrade your python3 to the versions Arch uses. I don't know if that will help, but it may be worth a try.  Other than that I'm out of ideas....

**Comment by rigzbe** [comment]
I'm lazy man, I moved to Arch - now is working great, and I figured out something else, applet is not working with Gtk3 version of MATE ;) just informing.

**Comment by robint99** [comment]
No problem....  The Gtk3 thing is something I'm aware of and will get around to looking at when real life allows :)

**Comment by Duncaen** [comment]
You do realize, that the - and _ respectively in arch and voids package versions are just extra numbers for the times the package is changed in the repository without pushing the version, probably for template/pkgbuild changes and if they wouldn't be they would be really minor changes and shouldn't break anything.

Then you need `python3.4-gobject`, `python3.4-cairo` and `python3.4-xdg`.
Its not that hard, to just find the right packages for the right python version.

Btw voids mate uses Gtk3 too.
