### ISSUE TITLE
Scipy

### ISSUE THREAD

**Issue by dvrhax** [robint99/dock-applet#33]
Just an FYI that after I installed it and tried to add it to the panel the app crashed because it couldn't import scipy.  Everything works great after installing scipy but may want to add it as a dependancy.  Great program though.  Just what I was hoping I could get DockbarX to be.

**Comment by robint99** [comment]
Scipy was already listed in the dependencies. However, since you're not the first person to miss it I've changed the installation instructions so that the dependencies are listed there. Its probably where they should probably have been in the first place :)

Glad you like the applet!

**Comment by dvrhax** [comment]
I should have been more specific.  I installed it from the ppa and it didn't pull down scipy as a dependency. So I think its something in the deb file.  Thanks again for the great product.
