### ISSUE TITLE
don't ship build cruft in Git tree

### ISSUE THREAD

**Issue by sunweaver** [robint99/dock-applet#36]
You have many files in your Git tree that are considered build cruft.

Here is a list:

-rw-r--r-- 1 mike mike  48031 Jan  8 13:20 aclocal.m4

-> remove

-rw-r--r-- 1 mike mike     15 Jan  8 13:20 AUTHORS

-> OK

-rw-r--r-- 1 mike mike   6796 Jan  8 13:20 ChangeLog

-> OK. Reversing order may be nice (most recent release at the top)

-rwxr-xr-x 1 mike mike 121470 Jan  8 13:20 configure

-> remove

-rw-r--r-- 1 mike mike    792 Jan  8 13:20 configure.ac

-> OK

lrwxrwxrwx 1 mike mike     32 Jan  8 13:20 COPYING -> /usr/share/automake-1.15/COPYING

-> requires to be a real file

-rw-r--r-- 1 mike mike 170420 Jan  8 13:20 dock-applet-0.64.tar.gz

-> remove!!! See #34 

-rw-r--r-- 1 mike mike     66 Jan  8 13:20 .gitignore

-> maybe all to-be-remove build cruft files should be added to .gitignore

lrwxrwxrwx 1 mike mike     32 Jan  8 13:20 INSTALL -> /usr/share/automake-1.15/INSTALL

-> remove

lrwxrwxrwx 1 mike mike     35 Jan  8 13:20 install-sh -> /usr/share/automake-1.15/install-sh

-> remove

-rw-r--r-- 1 mike mike  24354 Jan  8 13:20 Makefile

-> remove, should get re-created by autoconf/autotools

-rw-r--r-- 1 mike mike     14 Jan  8 13:20 Makefile.am

-> OK

-rw-r--r-- 1 mike mike  23945 Jan  8 13:20 Makefile.in

-> remove, should get re-created by autoconf

lrwxrwxrwx 1 mike mike     32 Jan  8 13:20 missing -> /usr/share/automake-1.15/missing

-> remove

-rw-r--r-- 1 mike mike   1356 Jan  8 13:20 NEWS

-> OK

lrwxrwxrwx 1 mike mike     35 Jan  8 13:20 py-compile -> /usr/share/automake-1.15/py-compile

-> remove

-rw-r--r-- 1 mike mike    726 Jan  8 13:20 README

-> OK, maybe redundant info that should be in README.md

-rw-r--r-- 1 mike mike   2487 Jan  8 13:20 README.md

-> OK

drwxr-xr-x 2 mike mike   4096 Jan  8 13:20 src

-> OK

drwxr-xr-x 2 mike mike   4096 Jan  8 13:20 src/Makefile.in

-> remove

A quick action on this one will be highly appreciated!!!

Mike

**Comment by robint99** [comment]
Hi,

I've made the changes you suggested and bumped the version number to 0.67. Let me know if all is ok now, or if there are any changes you need.

Cheers,

Robin

**Comment by sunweaver** [comment]
Hi Robin,

On  Di 09 Feb 2016 12:13:45 CET, robint99 wrote:

> I've made the changes you suggested and bumped the version number to  
> 0.67. Let me know if all is ok now, or if there are any changes you  
> need.

Looks all good to me now. Please close issues #34, #35, #36.

Mike

-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de
