### ISSUE TITLE
Dependancy

### ISSUE THREAD

**Issue by dvrhax** [robint99/dock-applet#37]
Ran into another dependancy issue trying to install on a fresh install of Ubuntu Mate.  After trying to add the dock I got a crash with this error:
keyerror 'could not find foreign type context'
Gdk.cairo_set_source_pixbuf(ctx, self.app_pb, 3, 3)

Did some searching and found that I had to install: python3-gi-cairo

Works great now.

**Comment by robint99** [comment]
Thanks for the info. I'll add this to the README and close this issue...

Cheers.
