### ISSUE TITLE
(dist)clean rule do not clean up properly

### ISSUE THREAD

**Issue by sunweaver** [robint99/dock-applet#38]
The Makefile does not handle proper source tree clean-up so well. Mostly because of commented out code in src/Makefile.am.

When doing .deb package rebuilds, I tend to like builds being idempotent. (That means, I would love to be able to rebuild packages several times. This requires that debian/rules clean returns the source tree into its original state).

URL to patch proposal comes shortly...

**Comment by sunweaver** [comment]
http://anonscm.debian.org/cgit/pkg-mate/mate-dock-applet.git/tree/debian/patches/1001_proper-make-clean.patch

**Comment by robint99** [comment]
I've applied all of the patches and committed the changes. If there's anything else you need doing for this (e.g. a bump in version number) just let me know.

Cheers
