### ISSUE TITLE
Can't open pinned Caja window

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/dock-applet#4]
When I pin Caja to the Dock Applet, I can't open a new instance from it. The Icon indicates to open it but then nothing happens. I've installed Nautilus and tried the same, opens fine, so it seems to be a Caja specific problem.

Probably this happens because the dock tries to start the caja session, instead of the application.

---
Linux Mint 17.1 x64
Mate 1.8.1

**Comment by robint99** [comment]
I've had a look at this and got a fix ready for the next version of the applet, which I should hopefully be able to release within the next week,

Cheers.

**Comment by robint99** [comment]
I've just uploaded V0.61 of the applet to git and the AUR, so hopefully the Webupd8 PPA will follow shortly..

**Comment by NoXPhasma** [comment]
I've compiled it on my own and it works fine. Thank you!

**Comment by karas84** [comment]
Don't know if it's related to this but I can't seem to open a new instance of an application that is already open. Suppose I open a terminal and I want to open a new one. Usually on other docks there is an entry on the right-click menu to open a new instance but I can't seem to find anything similiar here.

**Comment by robint99** [comment]
If you have version 0.61 of the applet you can shift left click on a
running application icon to open another instance.

Cheers
