### ISSUE TITLE
Question about Munity configurability

### ISSUE THREAD

**Issue by marksev1** [robint99/dock-applet#42]
Hi robint99,

Will the implementation of the dock-applet in Ubuntu Mate be flexible enough to be able to change layouts, for example to change the Munity layout to "Windows 7 style layout"? In some config file or something?

Thanks!

**Comment by robint99** [comment]
Hi,

There isn't a Windows 7 layout included in Ubuntu Mate but Mate makes it
extremely easy to configure panels and applets. You can add a panel to any
side of the screen and put whatever applets you want on it and then adjust
things just as you want. Here's my own Window's 7 style panel...
[image: Inline image 1]

The first button is the Menu applet. Following that  is the dock applet, a
weather applet, notification area applet, calendar applet and shut down
applet.

Hope this is helpful ....

**Comment by marksev1** [comment]
Cool, thanks! Closing issue :)
