### ISSUE TITLE
As a window list replacement, it stinks.

### ISSUE THREAD

**Issue by Hebgbs** [robint99/dock-applet#48]
...Though, I get it. The window list applet that is bog-standard in most Ubuntu MATE and Linux Mint installations have been around the block a few times in its life. But even as a window selector replacement, I wouldn't bet my life on it.

This has nothing to do with using soreau's backported Compiz either; The window list is still better than your dock at taking me to a specific window, in a specific workspace. Further, it's better at identifying different windows, using only window titles, not program classes or some other convoluted method of determining how the program is displayed.

I use Terminator as my terminal emulator. Why is Terminator called "Root terminal" ? I use Electric Sheep. Why does that come up as a unknown window? An icon is blinking; I expect to click on it and have the program take me to a window that is attention-demanding. Instead it acts retarded. Not even clicking on the specific window from the blinking icon takes me where I need to be. What? Why?!

Even old, crippled Avant Window Navigator from awn-testing's Saucy repo does better than this. I don't want to say any of the above, and I certainly don't want to demerit your work so harshly as this is still a new-ish project, but this still has a rather long way to go before it can truly be used as a drop-in replacement for the stock window list.

Could I be using it the wrong way? That's entirely possible. But people are going to want to use this as a window list replacement, and they'll be sadly disappointed at how incapable it seems with handling basic tasks.

**Comment by robint99** [comment]
Closing this 'issue' as the poster is obviously trolling

**Comment by soreau** [comment]
Hi @robint99, I'm from the compiz-reloaded project. Hebgbs was interested in being unbanned from this project but he does not have a way to contact you. If you would consider it, I am asking on his behalf because he cannot contact you.
