### ISSUE TITLE
Weird focus order after bringing windows back to focus

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/dock-applet#5]
When I click on a icon which has several instances, the focus order is in order of the opening time, instead of the last focus order. This can be very frustrating when you change to a different program and goes back to the previews program which has several instances. Instead of focus the last focused window, it always has focus on the first opened instance.

I really think it should have focus on the last focused instance instead.

**Comment by robint99** [comment]
I agree. I'll have a look at sorting it out for V0.62

Cheers

**Comment by sandikata** [comment]
offtopic. what version of mate is supported ?

1.6 , 1.8 or newer ?

**Comment by robint99** [comment]
I suppose it's 1.8.1 because it's the only version I've actually tried it on. In theory though it should work on older versions because I don't GTK2 or the python bindings the applet uses have changed in quite some time.

**Comment by robint99** [comment]
The focus order problem has been fixed in the latest version of the applet, which I've just uploaded to github. 

Enjoy!

**Comment by NoXPhasma** [comment]
Works like a charm, thank you!

**Comment by NoXPhasma** [comment]
Well, I found a small bug with the new focus. It brings the last used window to the front, but does not focus it in some cases.

It works very well as long as I've focus on a different window before. But when I just minimize the windows with the launcher and unminimize it, it does not focus the window. I need to click the launcher again to get focus on the front window in this case.

**Comment by robint99** [comment]
Thanks, I'll take a look at it. Are there any particular programs this happens with, or does it affect all apps?

**Comment by NoXPhasma** [comment]
I've tried Mate-terminal, Caja and Geany. It happened to all of them. So it might happen to every program.

**Comment by robint99** [comment]
I managed to duplicate problem on my PC and I've now fixed it. The code has just been pushed to github so you can get hold of it from there if you don't want to wait for the next version of the applet to be released.

**Comment by NoXPhasma** [comment]
Yep, works now as it should. Thanks again for your work, I love this dock!
